it.only('login test', function() {
    cy.visit('https://cms.mysuperindo.co.id/')
    cy.get(':nth-child(3) > .uk-inline > .uk-input').type('fadli')
    cy.get('.parent-password-form > .uk-inline > .uk-input').click()
    cy.get('.parent-password-form > .uk-inline > .uk-input').type('Brilliant77!')
    cy.get('.uk-button.uk-width-1-1').click()
    cy.wait(1000)
    cy.get('.active').click()
    cy.wait(1000)
    cy.get(':nth-child(1) > .router-link-active > .uk-nav > .uk-parent > .uk-nav-sub > :nth-child(2)').click()
    cy.wait(1000)
    cy.get(':nth-child(1) > .router-link-active > .uk-nav > .uk-parent > .uk-nav-sub > :nth-child(3)').click()
    cy.wait(1000)
    cy.get(':nth-child(1) > .router-link-active > .uk-nav > .uk-parent > .uk-nav-sub > :nth-child(4)').click()
    cy.wait(1000)
    cy.get(':nth-child(1) > .router-link-active > .uk-nav > .uk-parent > .uk-nav-sub > :nth-child(5)').click()
    cy.wait(1000)
    cy.get(':nth-child(1) > .router-link-active > .uk-nav > .uk-parent > .uk-nav-sub > :nth-child(6)').click()
})